name: Publish to Azure (dev - push)
on:
  push:
    branches:
      - dev
jobs:
  publish-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://${{ vars.AZ_ACCOUNT_NAME }}.blob.core.windows.net/${{ vars.AZ_CONTAINER_NAME }}
    name: Publish (dev)
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v4
      - name: Install Node
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        id: ci
        run: npm ci
      - name: Build/Pack Distro
        id: buildpack
        run: npm run pack
      - name: Zip Distro
        id: zip
        run: |
          zip -r ${{ vars.AZ_CONTAINER_DESTINATION_PATH }}.zip ${{ vars.AZ_CONTAINER_DESTINATION_PATH }}
      - name: Azure - Publish New Distro
        id: pubnew
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload -c '${{ vars.AZ_CONTAINER_NAME }}' -f '${{ vars.AZ_CONTAINER_DESTINATION_PATH }}.zip' -n '${{ vars.AZ_CONTAINER_DESTINATION_PATH }}.zip' --overwrite 'true' --account-name '${{ vars.AZ_ACCOUNT_NAME }}' --sas-token '${{ secrets.AZ_CONTAINER_SAS_TOKEN }}'
