name: Publish to Azure (dev - push)
on:
  push:
    branches:
      - dev
jobs:
  publish-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://${{ vars.AZ_ACCOUNT }}.blob.core.windows.net/${{ vars.AZ_CONTAINER }}/${{ vars.PACKAGE }}.zip
    name: Publish (dev)
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v4
      - name: Install Node
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        id: ci
        run: npm ci
      - name: Build/Pack Distro
        id: buildpack
        run: npm run pack
      - name: Zip Distro
        id: zip
        run: |
          zip -r ${{ vars.PACKAGE }}.zip ${{ vars.PACKAGE }}
      - name: Azure - Publish Distro
        id: pub
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload -c ${{ vars.AZ_CONTAINER }} -f ${{ vars.PACKAGE }}.zip -n ${{ vars.PACKAGE }}.zip --overwrite true --account-name ${{ vars.AZ_ACCOUNT }} --sas-token '${{ secrets.AZ_CONTAINER_SAS_TOKEN }}'
